### ISSUE TITLE
Comment files

### ISSUE THREAD

**Issue by TimVosch** [Ideetron/RFM95W_Nexus#6]
Please add comments or a guide somewhere, this is not understandable

**Comment by GerbendH** [comment]
All code is based on the LoRaWAN specification and the RFM95 datasheet. See enclosed documents

[LoRaWAN Specification 1R0.pdf](https://github.com/Ideetron/RFM95W_Nexus/files/594332/LoRaWAN.Specification.1R0.pdf)
[RFM95_96_97_98W.pdf](https://github.com/Ideetron/RFM95W_Nexus/files/594334/RFM95_96_97_98W.pdf)
